//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipeWorkshopApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Создание_IP {
            get {
                return ((string)(this["Создание_IP"]));
            }
            set {
                this["Создание_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Создание_Port {
            get {
                return ((int)(this["Создание_Port"]));
            }
            set {
                this["Создание_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Создание_Register {
            get {
                return ((int)(this["Создание_Register"]));
            }
            set {
                this["Создание_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Шарошка_Good_IP {
            get {
                return ((string)(this["Шарошка_Good_IP"]));
            }
            set {
                this["Шарошка_Good_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Шарошка_Good_Port {
            get {
                return ((int)(this["Шарошка_Good_Port"]));
            }
            set {
                this["Шарошка_Good_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Шарошка_Good_Register {
            get {
                return ((int)(this["Шарошка_Good_Register"]));
            }
            set {
                this["Шарошка_Good_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Шарошка_Reject_IP {
            get {
                return ((string)(this["Шарошка_Reject_IP"]));
            }
            set {
                this["Шарошка_Reject_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Шарошка_Reject_Port {
            get {
                return ((int)(this["Шарошка_Reject_Port"]));
            }
            set {
                this["Шарошка_Reject_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Шарошка_Reject_Register {
            get {
                return ((int)(this["Шарошка_Reject_Register"]));
            }
            set {
                this["Шарошка_Reject_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Токарка_IP {
            get {
                return ((string)(this["Токарка_IP"]));
            }
            set {
                this["Токарка_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Токарка_Port {
            get {
                return ((int)(this["Токарка_Port"]));
            }
            set {
                this["Токарка_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Токарка_Register {
            get {
                return ((int)(this["Токарка_Register"]));
            }
            set {
                this["Токарка_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Отворот_IP {
            get {
                return ((string)(this["Отворот_IP"]));
            }
            set {
                this["Отворот_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Отворот_Port {
            get {
                return ((int)(this["Отворот_Port"]));
            }
            set {
                this["Отворот_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Отворот_Register {
            get {
                return ((int)(this["Отворот_Register"]));
            }
            set {
                this["Отворот_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Опрессовка_Good_IP {
            get {
                return ((string)(this["Опрессовка_Good_IP"]));
            }
            set {
                this["Опрессовка_Good_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Опрессовка_Good_Port {
            get {
                return ((int)(this["Опрессовка_Good_Port"]));
            }
            set {
                this["Опрессовка_Good_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Опрессовка_Good_Register {
            get {
                return ((int)(this["Опрессовка_Good_Register"]));
            }
            set {
                this["Опрессовка_Good_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Опрессовка_Reject_IP {
            get {
                return ((string)(this["Опрессовка_Reject_IP"]));
            }
            set {
                this["Опрессовка_Reject_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Опрессовка_Reject_Port {
            get {
                return ((int)(this["Опрессовка_Reject_Port"]));
            }
            set {
                this["Опрессовка_Reject_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Опрессовка_Reject_Register {
            get {
                return ((int)(this["Опрессовка_Reject_Register"]));
            }
            set {
                this["Опрессовка_Reject_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Маркировка_IP {
            get {
                return ((string)(this["Маркировка_IP"]));
            }
            set {
                this["Маркировка_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Маркировка_Port {
            get {
                return ((int)(this["Маркировка_Port"]));
            }
            set {
                this["Маркировка_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Маркировка_Register {
            get {
                return ((int)(this["Маркировка_Register"]));
            }
            set {
                this["Маркировка_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Карманы_IP {
            get {
                return ((string)(this["Карманы_IP"]));
            }
            set {
                this["Карманы_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Карманы_Port {
            get {
                return ((int)(this["Карманы_Port"]));
            }
            set {
                this["Карманы_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Карманы_Register {
            get {
                return ((int)(this["Карманы_Register"]));
            }
            set {
                this["Карманы_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerIP {
            get {
                return ((string)(this["ServerIP"]));
            }
            set {
                this["ServerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ServerPort {
            get {
                return ((int)(this["ServerPort"]));
            }
            set {
                this["ServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Otvorot_DeviceURL4 {
            get {
                return ((string)(this["Otvorot_DeviceURL4"]));
            }
            set {
                this["Otvorot_DeviceURL4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string НК_Good_IP {
            get {
                return ((string)(this["НК_Good_IP"]));
            }
            set {
                this["НК_Good_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int НК_Good_Port {
            get {
                return ((int)(this["НК_Good_Port"]));
            }
            set {
                this["НК_Good_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int НК_Good_Register {
            get {
                return ((int)(this["НК_Good_Register"]));
            }
            set {
                this["НК_Good_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string НК_Reject_IP {
            get {
                return ((string)(this["НК_Reject_IP"]));
            }
            set {
                this["НК_Reject_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int НК_Reject_Port {
            get {
                return ((int)(this["НК_Reject_Port"]));
            }
            set {
                this["НК_Reject_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int НК_Reject_Register {
            get {
                return ((int)(this["НК_Reject_Register"]));
            }
            set {
                this["НК_Reject_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TriggerDelay {
            get {
                return ((int)(this["TriggerDelay"]));
            }
            set {
                this["TriggerDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Karman1BatchNumber {
            get {
                return ((int)(this["Karman1BatchNumber"]));
            }
            set {
                this["Karman1BatchNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Karman1BatchCount {
            get {
                return ((int)(this["Karman1BatchCount"]));
            }
            set {
                this["Karman1BatchCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Karman2BatchNumber {
            get {
                return ((int)(this["Karman2BatchNumber"]));
            }
            set {
                this["Karman2BatchNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Karman2BatchCount {
            get {
                return ((int)(this["Karman2BatchCount"]));
            }
            set {
                this["Karman2BatchCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Karman3BatchNumber {
            get {
                return ((int)(this["Karman3BatchNumber"]));
            }
            set {
                this["Karman3BatchNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Karman3BatchCount {
            get {
                return ((int)(this["Karman3BatchCount"]));
            }
            set {
                this["Karman3BatchCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Karman4BatchNumber {
            get {
                return ((int)(this["Karman4BatchNumber"]));
            }
            set {
                this["Karman4BatchNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Karman4BatchCount {
            get {
                return ((int)(this["Karman4BatchCount"]));
            }
            set {
                this["Karman4BatchCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KarmanIp1 {
            get {
                return ((string)(this["KarmanIp1"]));
            }
            set {
                this["KarmanIp1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KarmanPort1 {
            get {
                return ((int)(this["KarmanPort1"]));
            }
            set {
                this["KarmanPort1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KarmanRegister1 {
            get {
                return ((int)(this["KarmanRegister1"]));
            }
            set {
                this["KarmanRegister1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KarmanIp2 {
            get {
                return ((string)(this["KarmanIp2"]));
            }
            set {
                this["KarmanIp2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KarmanPort2 {
            get {
                return ((int)(this["KarmanPort2"]));
            }
            set {
                this["KarmanPort2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KarmanRegister2 {
            get {
                return ((int)(this["KarmanRegister2"]));
            }
            set {
                this["KarmanRegister2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KarmanIp3 {
            get {
                return ((string)(this["KarmanIp3"]));
            }
            set {
                this["KarmanIp3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KarmanPort3 {
            get {
                return ((int)(this["KarmanPort3"]));
            }
            set {
                this["KarmanPort3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KarmanRegister3 {
            get {
                return ((int)(this["KarmanRegister3"]));
            }
            set {
                this["KarmanRegister3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KarmanIp4 {
            get {
                return ((string)(this["KarmanIp4"]));
            }
            set {
                this["KarmanIp4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KarmanPort4 {
            get {
                return ((int)(this["KarmanPort4"]));
            }
            set {
                this["KarmanPort4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KarmanRegister4 {
            get {
                return ((int)(this["KarmanRegister4"]));
            }
            set {
                this["KarmanRegister4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Karman1BatchSize {
            get {
                return ((int)(this["Karman1BatchSize"]));
            }
            set {
                this["Karman1BatchSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Karman2BatchSize {
            get {
                return ((int)(this["Karman2BatchSize"]));
            }
            set {
                this["Karman2BatchSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Karman3BatchSize {
            get {
                return ((int)(this["Karman3BatchSize"]));
            }
            set {
                this["Karman3BatchSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Karman4BatchSize {
            get {
                return ((int)(this["Karman4BatchSize"]));
            }
            set {
                this["Karman4BatchSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Karman1_Diameter {
            get {
                return ((string)(this["Karman1_Diameter"]));
            }
            set {
                this["Karman1_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Karman1_Material {
            get {
                return ((string)(this["Karman1_Material"]));
            }
            set {
                this["Karman1_Material"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Karman1_Group {
            get {
                return ((string)(this["Karman1_Group"]));
            }
            set {
                this["Karman1_Group"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Karman2_Diameter {
            get {
                return ((string)(this["Karman2_Diameter"]));
            }
            set {
                this["Karman2_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Karman2_Material {
            get {
                return ((string)(this["Karman2_Material"]));
            }
            set {
                this["Karman2_Material"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Karman2_Group {
            get {
                return ((string)(this["Karman2_Group"]));
            }
            set {
                this["Karman2_Group"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Karman3_Diameter {
            get {
                return ((string)(this["Karman3_Diameter"]));
            }
            set {
                this["Karman3_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Karman3_Material {
            get {
                return ((string)(this["Karman3_Material"]));
            }
            set {
                this["Karman3_Material"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Karman3_Group {
            get {
                return ((string)(this["Karman3_Group"]));
            }
            set {
                this["Karman3_Group"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Karman4_Diameter {
            get {
                return ((string)(this["Karman4_Diameter"]));
            }
            set {
                this["Karman4_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Karman4_Material {
            get {
                return ((string)(this["Karman4_Material"]));
            }
            set {
                this["Karman4_Material"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Karman4_Group {
            get {
                return ((string)(this["Karman4_Group"]));
            }
            set {
                this["Karman4_Group"] = value;
            }
        }
    }
}
